export const Endpoints = {
    HOME:"/",
    LOGIN:"/login",
    SIGNUP:"/signup",
    LOGOUT:"/logout",
    PROFILE:"/profile",
    FORGOT_PASSWORD:"/forgot-password",
    NOTIFICATIONS:"/notifications",
    SETTINGS:"/settings",
    YOUR_GROUPS:"/your-groups",
    NEW_GROUP:"/create-group",
    EDIT_GROUP:"/edit-group/:id",
    YOUR_EVENTS:"/your-events",
    NEW_EVENT:"/new-event",
    EDIT_EVENT:"/edit-event/:id",
    GROUPS_ORGANIZED_BY_USER: "/groups-organized-by-user",
    TAGS:"/tags",
}
